#!/usr/bin/env bash
# Phase 2 — Step 2: Install and configure stunnel on the EC2 proxy.
#
# RUN THIS ON THE EC2 INSTANCE (i-03ed3c733f414b462), via EC2 Instance
# Connect or your existing SSH session — not locally.
#
# Before running, copy these three files onto the instance (scp, or paste
# via Instance Connect's file upload / a heredoc — never through a public
# S3 bucket or anything world-readable):
#   ca.crt      (from infra/mtls-relay/certs/, generated by 01-generate-ca-and-certs.sh)
#   server.crt
#   server.key
#
# e.g. from your laptop:
#   scp -i <your-ec2-key>.pem infra/mtls-relay/certs/{ca.crt,server.crt,server.key} \
#       ec2-user@13.63.60.102:/tmp/
#
# Then SSH/Instance-Connect in and run this script with sudo.

set -euo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "Run as root: sudo bash 02-install-stunnel.sh" >&2
  exit 1
fi

echo "== Installing stunnel =="
if command -v dnf >/dev/null 2>&1; then
  dnf install -y stunnel
elif command -v yum >/dev/null 2>&1; then
  amazon-linux-extras install -y epel 2>/dev/null || true
  yum install -y stunnel
else
  echo "Unrecognized distro — install stunnel manually, then re-run from the cert-copy step." >&2
  exit 1
fi

echo "== Placing certs =="
mkdir -p /etc/stunnel/certs
for f in ca.crt server.crt server.key; do
  if [[ -f "/tmp/$f" ]]; then
    cp "/tmp/$f" "/etc/stunnel/certs/$f"
  elif [[ ! -f "/etc/stunnel/certs/$f" ]]; then
    echo "Missing /tmp/$f and no existing /etc/stunnel/certs/$f — copy it up first." >&2
    exit 1
  fi
done
chown -R root:root /etc/stunnel/certs
chmod 600 /etc/stunnel/certs/server.key
chmod 644 /etc/stunnel/certs/server.crt /etc/stunnel/certs/ca.crt
# server.key only needs to exist on this box — wipe the /tmp copy either way
shred -u /tmp/server.key 2>/dev/null || rm -f /tmp/server.key

echo "== Installing stunnel.conf =="
cp "$(dirname "$0")/stunnel.conf" /etc/stunnel/stunnel.conf

mkdir -p /var/log/stunnel /var/run/stunnel
chown -R nobody:nobody /var/log/stunnel /var/run/stunnel 2>/dev/null || true

echo "== Enabling stunnel systemd service =="
systemctl enable stunnel
systemctl restart stunnel
sleep 1
systemctl status stunnel --no-pager

echo
echo "Done. stunnel should now be listening on 0.0.0.0:8443 and forwarding"
echo "authenticated (mTLS) connections to 172.31.29.62:3306."
echo
echo "Next: run the Phase 2 tests in 03-test-checklist.md"
